ArgocdApplications:
  #=================================#
  #      Platform Core Apps         #
  #=================================#

  argocd-image-updater:
    enabled: false

  raw:
    enabled: true

  backstage:
    enabled: false

  #=================================#
  #      Data Services          #
  #=================================#

  database:
    enabled: true

  postgres-operator:
    enabled: true

  pgadmin:
    enabled: true

  redis:
    enabled: false

  #=================================#
  #      Network Services           #
  #=================================#

  metallb:
    enabled: true
    ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        name: bgppeers.metallb.io
        jsonPointers:
          - /spec/conversion/webhook/clientConfig/caBundle

  external-dns:
    enabled: true

  ingress-nginx-internal:
    enabled: true

  ingress-nginx-external:
    enabled: true

  cilium:
    enabled: false

  #=================================#
  #      Security & Auth            #
  #=================================#

  keycloak:
    enabled: true
    # syncWave: 1

  keycloak-operator:
    enabled: true

  cert-manager:
    enabled: true

  vault:
    enabled: false

  sealed-secrets:
    enabled: false

  oauth2-proxy:
    enabled: false
    # syncWave: 2

  external-secrets:
    enabled: false

  kyverno:
    enabled: false

  #=================================#
  #      Monitoring Stack           #
  #=================================#

  dashboards:
    enabled: true

  metrics-server:
    enabled: true

  kube-prometheus-stack:
    enabled: true

  loki:
    enabled: true

  promtail:
    enabled: true

  #=================================#
  #      Example Applications       #
  #=================================#

  show-env:
    enabled: true
    annotations:
      argocd-image-updater.argoproj.io/image-list: ghcr.io/kuberise/show-env:latest
      argocd-image-updater.argoproj.io/update-strategy: digest
      argocd-image-updater.argoproj.io/write-back-method: git

  frontend-https:
    enabled: true

  backend:
    enabled: true
